name: Symfony CI

on: [push]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          coverage: pcov

      - name: Install dependencies
        run: composer install --no-progress --prefer-dist

      - name: Run PHP-CS-Fixer
        run: ./vendor/bin/php-cs-fixer fix --dry-run --diff

      - name: Run PHP lint
        run: find src tests -name "*.php" -exec php -l {} \;

      - name: Run PHPStan
        run: ./vendor/bin/phpstan analyse

      - name: Run PHPUnit
        run: ./vendor/bin/phpunit --coverage-text --coverage-clover=coverage.xml

      - name: Audit de sécurité
        run: composer audit --format=json --no-interaction
        continue-on-error: true # Permettre au CI de continuer même si des vulnérabilités sont détectées

      - name: Set Environment variables
        run: 'export APP_ENV=prod && export DATABASE_URL=${{ secrets.DATABASE_URL }}'

      - name: Dump env
        run: composer dump-env prod

      - name: Install dependencies
        run: composer install --no-dev --optimize-autoloader --ignore-platform-reqs

      - name: Optimize assets
        run: php bin/console asset-map:compile

      - name: Create archive
        run: tar -czvf symfony-artifact-r1.tar.gz \
          --exclude=.git \
          --exclude=node_modules \
          --exclude=var/cache \
          --exclude=var/log \
          --exclude=tests \
          --exclude=.env \
          --exclude=docker \
          --exclude=docker-compose.yml \
          --exclude=README.md \
          --exclude=*.log \
          --exclude=*.gitignore \
          .
